---
- name: Install Packages
  apt: name={{ item }} state=present
  with_items:
    - bareos-storage

- name: Create storage location

  file: path={{ item }} owner=bareos group=bareos  mode=0770 state=directory
  with_items:
    - "{{ storage_location }}-1"
    - "{{ storage_location }}-2"

- name: mount nfs storages
  when: storage_on_nfs
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    opts: rw,nolock
    fstype: nfs
    state: mounted
  with_items:
      - { src: "{{storage1_nfs_host}}:{{ storage1_nfs_path }}", path: "{{ storage_location }}-1" }
      - { src: "{{storage2_nfs_host}}:{{ storage2_nfs_path }}", path: "{{ storage_location }}-2" }

- name: Push Bareos-Storage configuration files
  template: src={{item.src}} dest={{item.dest}}  mode=0640 owner=bareos group=bareos
  with_items:
      - { src: 'device/FileStorage.conf', dest: '/etc/bareos/bareos-sd.d/device/FileStorage.conf' }
      - { src: 'director/bareos-dir.conf', dest: '/etc/bareos/bareos-sd.d/director/bareos-dir.conf' }
      - { src: 'messages/Standard.conf', dest: '/etc/bareos/bareos-sd.d/messages/Standard.conf' }
      - { src: 'storage/bareos-sd.conf', dest: '/etc/bareos/bareos-sd.d/storage/bareos-sd.conf' }
  notify: reload bareos-storage

- name: Enable bareos storage service
  action: service name=bareos-sd state=started enabled=yes

