---
- name: add bareos key
  apt_key: url="http://download.bareos.org/bareos/release/{{ bareos_version }}/xUbuntu_{{ ansible_distribution_version }}/Release.key" state=present

- name: add bareos repo
  apt_repository: repo="deb http://download.bareos.org/bareos/release/{{ bareos_version }}/xUbuntu_{{ ansible_distribution_version }}/ /" state=present update_cache=yes
